### ISSUE TITLE
Line numbers

### ISSUE THREAD

**Issue by jamaa** [readchu/regsearch#1]
Instead of determining the line number of matches by searching for the line in `all_lines' like here: https://github.com/readchu/regsearch/blob/071d5d0d869a3107a26af74aef167f72eb561b95/regsearch.py#L63

it may be faster to use `enumerate` like this:
```python
                for line_num, line in enumerate(all_lines, start=1):
                    if regex.search(line):
                        [...]
                        entry = f"Match #{match_num}, Line {line_num}: {line}"
```

**Comment by readchu** [comment]
Thanks, Felix - that makes a lot of sense.
